# Generated by Django 5.2.8 on 2025-12-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Mã hạng phòng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hạng phòng')),
                ('base_price_hourly', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá theo giờ')),
                ('base_price_daily', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá theo ngày')),
                ('base_price_overnight', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá qua đêm')),
                ('early_checkin_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phụ thu nhận sớm (/h)')),
                ('late_checkout_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phụ thu trả muộn (/h)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_classes', to='hotel.branch', verbose_name='Chi nhánh')),
            ],
            options={
                'verbose_name': 'Hạng phòng',
                'verbose_name_plural': 'Danh sách Hạng phòng',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Số phòng (Tên)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Phòng trống'), ('OCCUPIED', 'Đang có khách'), ('DIRTY', 'Chưa dọn'), ('FIXING', 'Đang bảo trì')], default='AVAILABLE', max_length=20, verbose_name='Trạng thái')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotel.area', verbose_name='Khu vực/Tầng')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.branch', verbose_name='Chi nhánh')),
                ('room_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel.roomclass', verbose_name='Hạng phòng')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Danh sách Phòng',
            },
        ),
    ]
