# Generated by Django 5.2.8 on 2025-12-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_product_serviceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accompanying_people',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='identity_type',
            field=models.CharField(choices=[('CCCD', 'CCCD/CMND'), ('PASSPORT', 'PASSPORT'), ('DRIVER_LICENSE', 'Giấy phép lái xe')], default='CCCD', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
