# Generated by Django 5.2.8 on 2025-12-02 02:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_customer_accompanying_people_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accompanying_people',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entourage', to='hotel.customer'),
        ),
    ]
