# Generated by Django 5.2.8 on 2025-12-02 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_customer_accompanying_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('RECEIPT', 'Phiếu Thu'), ('PAYMENT', 'Phiếu Chi')], max_length=20)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.branch')),
            ],
        ),
    ]
