# Generated by Django 5.2.8 on 2025-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_expected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='check_in_actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
