# Generated by Django 5.2.8 on 2025-12-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_booking_check_in_expected_booking_check_out_expected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingroom',
            old_name='price_hourly_snapshot',
            new_name='price_snapshot',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='booking_type',
            field=models.CharField(choices=[('HOURLY', 'Theo giờ'), ('DAILY', 'Theo ngày'), ('OVERNIGHT', 'Qua đêm')], default='HOURLY', max_length=20),
        ),
    ]
