# Generated by Django 5.2.8 on 2025-12-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rename_price_hourly_snapshot_bookingroom_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='booking_type',
            field=models.CharField(choices=[('HOURLY', 'Theo giờ'), ('DAILY', 'Theo ngày'), ('OVERNIGHT', 'Qua đêm')], default='DAILY', max_length=20),
        ),
    ]
