# Generated by Django 5.2.8 on 2025-12-04 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_bookingroom_booking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên thiết bị')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã tài sản')),
                ('status', models.CharField(choices=[('GOOD', 'Hoạt động tốt'), ('BROKEN', 'Hỏng/Cần sửa'), ('MAINTENANCE', 'Đang bảo trì'), ('LIQUIDATED', 'Đã thanh lý')], default='GOOD', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_maintenance_required', models.BooleanField(default=False, verbose_name='Cần bảo trì định kỳ')),
                ('maintenance_interval_days', models.IntegerField(default=0, verbose_name='Chu kỳ (ngày)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Ngày bảo trì gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='hotel.area')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='hotel.branch')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Chi phí')),
                ('description', models.TextField(verbose_name='Nội dung công việc')),
                ('performer', models.CharField(max_length=255, verbose_name='Người thực hiện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hotel.device')),
            ],
        ),
    ]
