# Generated by Django 5.2.8 on 2025-12-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='Giờ nhận phòng chuẩn')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='Giờ trả phòng chuẩn')),
                ('overtime_method', models.CharField(choices=[('PERCENT', 'Theo phần trăm (%)'), ('FIXED', 'Theo số tiền cố định (VNĐ)')], default='PERCENT', max_length=10, verbose_name='Cách tính phụ thu quá giờ')),
                ('overtime_percent', models.IntegerField(default=10, verbose_name='Phụ thu (%/giờ)')),
                ('overtime_fixed', models.DecimalField(decimal_places=0, default=50000, max_digits=12, verbose_name='Phụ thu (VNĐ/giờ)')),
                ('overtime_threshold_hours', models.IntegerField(default=4, verbose_name='Giới hạn quá giờ (giờ) tính 1 ngày')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='hotel.branch')),
            ],
        ),
    ]
