# Generated by Django 5.2.8 on 2025-12-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_branchsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='price_config_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roomclass',
            name='hourly_price_config',
            field=models.JSONField(blank=True, default=list, verbose_name='Cấu hình giá theo giờ'),
        ),
    ]
