# Generated by Django 5.2.8 on 2025-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_bookingroom_price_config_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsetting',
            name='early_checkin_fixed',
            field=models.DecimalField(decimal_places=0, default=50000, max_digits=12, verbose_name='Phụ thu sớm (VNĐ/giờ)'),
        ),
        migrations.AddField(
            model_name='branchsetting',
            name='early_checkin_free_hours',
            field=models.IntegerField(default=1, verbose_name='Số giờ miễn phí'),
        ),
        migrations.AddField(
            model_name='branchsetting',
            name='early_checkin_method',
            field=models.CharField(choices=[('PERCENT', 'Theo phần trăm (%)'), ('FIXED', 'Theo số tiền cố định (VNĐ)')], default='PERCENT', max_length=10, verbose_name='Cách tính phụ thu sớm'),
        ),
        migrations.AddField(
            model_name='branchsetting',
            name='early_checkin_percent',
            field=models.IntegerField(default=10, verbose_name='Phụ thu sớm (%/giờ)'),
        ),
        migrations.AddField(
            model_name='branchsetting',
            name='early_checkin_threshold_hours',
            field=models.IntegerField(default=4, verbose_name='Giới hạn sớm (giờ) tính 1 ngày'),
        ),
    ]
