# Generated by Django 5.2.8 on 2025-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_branchsetting_early_checkin_fixed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions_config',
            field=models.JSONField(blank=True, default=list, verbose_name='Phân quyền chi tiết'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('MANAGER', 'Quản lý'), ('RECEPTIONIST', 'Lễ tân'), ('ACCOUNTANT', 'Kế toán'), ('HOUSEKEEPING', 'Buồng phòng')], default='RECEPTIONIST', max_length=20, verbose_name='Vai trò'),
        ),
    ]
