# Generated by Django 5.2.8 on 2025-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_user_permissions_config_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền đặt cọc'),
        ),
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.IntegerField(default=1, verbose_name='Số người dự kiến'),
        ),
    ]
